service: codelog-flask

frameworkVersion: ">=2.12.0 <3.0.0"

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.7
  memorySize: 128
  # https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
  apiGateway:
    shouldStartNameWithService: true
  # https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
  lambdaHashingVersion: 20201221

functions:
  endpoint:
    handler: wsgi_handler.handler
    events:
      - http: ANY /

custom:
  functionsBasePath: ${self:custom.projectRootPath}/src
  wsgi:
    app: endpoint.app
    pythonBin: python
  pythonRequirements:
    dockerizePip: false
  customDomain:
    domainName: ${file(${self:custom.projectRootPath}/conf/conf.json):DOMAIN}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  projectRootPath:
    ${opt:project_root_path, env:PROJECT_ROOT_PATH, '..'}

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-domain-manager
