service: codelog-flask

frameworkVersion: ">=2.12.0 <3.0.0"

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.7
  apiGateway:
    # https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
    shouldStartNameWithService: true

functions:
  endpoint:
    handler: wsgi_handler.handler
    events:
      - http: ANY /

custom:
  wsgi:
    app: endpoint.app
    pythonBin: python
  pythonRequirements:
    dockerizePip: false
  customDomain:
    domainName: ${file(../conf/conf.json):DOMAIN}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-domain-manager
